name: GitHub metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "master"
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: waynesg
          config_timezone: Asia/Shanghai
          config_order: base.header, isocalendar, base.repositories, followup, pagespeed
          config_padding: 10%
          use_prebuilt_image: master
          base: "header, repositories"
          plugin_isocalendar: yes
          #          plugin_isocalendar_duration: full-year
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_lines: yes
          plugin_traffic: yes


      - name: Personal metrics (additional)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: waynesg
          config_timezone: Asia/Shanghai
          config_order: habits, stargazers, languages, stargazers, topics, people
          config_padding: 10%
          use_prebuilt_image: master
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_stargazers: yes

          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_skipped: lowlighter

          plugin_topics: yes
          plugin_topics_mode: mastered

  
